import config from "@helpwave/eslint-config"

export default [
  ...config.nextExtension,
  {
    rules: {
      "semi": ["error", "never"],
      "quotes": ["error", "double", { avoidEscape: true, allowTemplateLiterals: true }],
      "@stylistic/quotes": ["error", "double", { avoidEscape: true, allowTemplateLiterals: true }],
      // New in eslint-plugin-react-hooks 7. The forms that copy props into local
      // state in an effect should be refactored, until then only warn.
      "react-hooks/set-state-in-effect": "warn",
    },
  },
  // Generated by Next.js
  {
    ignores: ["next-env.d.ts"],
  },
]

