"""Runs core's Airflow integration against a real Airflow.

The DAG generated by core is written into the DAG folder of a running
Airflow, registered, triggered, monitored and deleted again through the same
functions the workflow views use.

Skipped unless AIRFLOW_INTEGRATION_URL and AIRFLOW_INTEGRATION_DAG_DIR (a
directory mounted as the DAG folder of that Airflow) are set, see the
`airflow` CI workflow for how Airflow is started.
"""

import os
import time

import pytest
from services.workflow_service import airflow_client
from services.workflow_service.controllers import workflow_controller as wc
from services.workflow_service.schemas.compute_block import BlockStatus
from services.workflow_service.schemas.workflow import WorkflowStatus
from tests.sample_workflow import BLOCKS, PROJECT_UUID, sample_graph

AIRFLOW_URL = os.environ.get("AIRFLOW_INTEGRATION_URL")
DAG_DIR = os.environ.get("AIRFLOW_INTEGRATION_DAG_DIR")

pytestmark = pytest.mark.skipif(
    not (AIRFLOW_URL and DAG_DIR),
    reason="AIRFLOW_INTEGRATION_URL / AIRFLOW_INTEGRATION_DAG_DIR not set",
)

DAG_ID = wc.project_id_to_dag_id(PROJECT_UUID)


def _wait_for(predicate, timeout=120, interval=2):
    deadline = time.time() + timeout
    while time.time() < deadline:
        result = predicate()
        if result:
            return result
        time.sleep(interval)
    return predicate()


@pytest.fixture(scope="module", autouse=True)
def airflow_env():
    mp = pytest.MonkeyPatch()
    mp.setattr(wc.ENV, "AIRFLOW_HOST", AIRFLOW_URL)
    mp.setattr(
        wc.ENV, "AIRFLOW_USER", os.environ.get("AIRFLOW_INTEGRATION_USER",
                                               "airflow"),
    )
    mp.setattr(
        wc.ENV, "AIRFLOW_PASS", os.environ.get("AIRFLOW_INTEGRATION_PASS",
                                               "airflow"),
    )
    mp.setattr(wc, "DAG_DIRECTORY", DAG_DIR)
    airflow_client.invalidate_airflow_token()
    yield
    airflow_client.invalidate_airflow_token()
    mp.undo()


def test_workflow_lifecycle():
    dag_code = wc.generate_dag_code(
        sample_graph(), wc.init_templates(), DAG_ID, PROJECT_UUID,
    )
    wc.save_dag_to_file(dag_code, DAG_ID)

    # registration (the dag-processor picks the file up)
    assert wc.wait_for_dag_registration(DAG_ID, timeout=180, wait=2)
    assert DAG_ID in wc.get_all_dags()
    assert wc.get_latest_dag_run(PROJECT_UUID) is None
    assert wc.dag_status(PROJECT_UUID) == {}

    # trigger
    wc.trigger_workflow_run(DAG_ID)
    run_id = _wait_for(lambda: wc.get_latest_dag_run(PROJECT_UUID))
    assert run_id

    overview = wc.last_dag_run_overview([DAG_ID])
    assert set(overview) == {DAG_ID}
    status = WorkflowStatus.from_airflow_state(overview[DAG_ID].state)
    assert status in WorkflowStatus

    # task states are reported per compute block
    statuses = _wait_for(
        lambda: len(wc.dag_status(PROJECT_UUID)) == len(BLOCKS)
        and wc.dag_status(PROJECT_UUID),
    )
    assert set(statuses) == {str(b["uuid"]) for b in BLOCKS}
    assert set(statuses.values()) <= {s.value for s in BlockStatus}

    # delete
    wc.delete_dag_from_airflow(PROJECT_UUID)
    assert not os.path.exists(os.path.join(DAG_DIR, f"{DAG_ID}.py"))
    assert DAG_ID not in wc.get_all_dags()


def test_wrong_credentials_are_reported(monkeypatch):
    monkeypatch.setattr(wc.ENV, "AIRFLOW_PASS", "wrong")
    airflow_client.invalidate_airflow_token()
    with pytest.raises(RuntimeError, match="401"):
        airflow_client.get_airflow_config()
    airflow_client.invalidate_airflow_token()
