"""renaming and relationship fixes

Revision ID: 27c6d763ef0d
Revises: 18f3f9de3ea4
Create Date: 2025-02-25 18:46:42.619220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27c6d763ef0d'
down_revision: Union[str, None] = '18f3f9de3ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('cbc_url', sa.String(length=100), nullable=False))
    op.drop_column('blocks', 'priority_weight')
    op.drop_column('blocks', 'repo_url')
    op.drop_column('blocks', 'retry_delay')
    op.drop_column('blocks', 'retries')
    op.drop_constraint('fk_block_uuid', 'entrypoints', type_='foreignkey')
    op.drop_column('entrypoints', 'block_uuid')
    op.alter_column('inputoutputs', 'entrypoint_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inputoutputs', 'entrypoint_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('entrypoints', sa.Column('block_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_block_uuid', 'entrypoints', 'blocks', ['block_uuid'], ['uuid'], ondelete='CASCADE')
    op.add_column('blocks', sa.Column('retries', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('blocks', sa.Column('retry_delay', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('blocks', sa.Column('repo_url', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('blocks', sa.Column('priority_weight', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('blocks', 'cbc_url')
    # ### end Alembic commands ###
