"""selected_entrypoint not null

Revision ID: 3e343934a352
Revises: 27c6d763ef0d
Create Date: 2025-02-28 17:26:37.802267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e343934a352'
down_revision: Union[str, None] = '27c6d763ef0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blocks', 'selected_entrypoint_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blocks', 'selected_entrypoint_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
