"""add input output ids to up and downstreams

Revision ID: 6cd6311ab4fb
Revises: 3e343934a352
Create Date: 2025-03-02 20:35:50.702497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd6311ab4fb'
down_revision: Union[str, None] = '3e343934a352'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block_dependencies', sa.Column(
        'upstream_output_uuid', sa.UUID(), nullable=False))
    op.add_column('block_dependencies', sa.Column(
        'downstream_input_uuid', sa.UUID(), nullable=False))
    op.create_foreign_key('fk_upstream_output', 'block_dependencies', 'inputoutputs', [
                          'upstream_output_uuid'], ['uuid'], ondelete='CASCADE')
    op.create_foreign_key('fk_downstream_input', 'block_dependencies', 'inputoutputs', [
                          'downstream_input_uuid'], ['uuid'], ondelete='CASCADE')
    op.create_primary_key(
        'pk_block_dependencies',
        'block_dependencies',
        ['upstream_block_uuid', 'upstream_output_uuid',
            'downstream_block_uuid', 'downstream_input_uuid']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pk_block_dependencies',
                       'block_dependencies', type_='primary')

    op.drop_constraint('fk_downstream_input',
                       'block_dependencies', type_='foreignkey')
    op.drop_constraint('fk_upstream_output',
                       'block_dependencies', type_='foreignkey')
    op.drop_column('block_dependencies', 'downstream_input_uuid')
    op.drop_column('block_dependencies', 'upstream_output_uuid')
    # ### end Alembic commands ###
