"""temp

Revision ID: ac58fcb73c6e
Revises: 11cb4f286ec5
Create Date: 2024-10-21 16:40:37.443800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac58fcb73c6e'
down_revision: Union[str, None] = '11cb4f286ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stupid_change', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stupid_change')
    # ### end Alembic commands ###
