"""update delete constraints

Revision ID: b4509fba043b
Revises: 6cd6311ab4fb
Create Date: 2025-03-08 00:45:23.985496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4509fba043b'
down_revision: Union[str, None] = '6cd6311ab4fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blocks', 'project_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('fk_selected_entrypoint_uuid', 'blocks', type_='foreignkey')
    op.create_foreign_key('fk_selected_entrypoint_uuid', 'blocks', 'entrypoints', ['selected_entrypoint_uuid'], ['uuid'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_selected_entrypoint_uuid', 'blocks', type_='foreignkey')
    op.create_foreign_key('fk_selected_entrypoint_uuid', 'blocks', 'entrypoints', ['selected_entrypoint_uuid'], ['uuid'], ondelete='SET NULL')
    op.alter_column('blocks', 'project_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
