"""Add names to block_dependencies foreign key constraints

Revision ID: bf8bb8e597db
Revises: d96594e39ae6
Create Date: 2025-01-16 00:38:28.145629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8bb8e597db'
down_revision: Union[str, None] = 'd96594e39ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
