"""unique constraint across project and custom_name

Revision ID: cabd8077b788
Revises: b4509fba043b
Create Date: 2025-03-08 00:48:08.688131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cabd8077b788'
down_revision: Union[str, None] = 'b4509fba043b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('proj_name_1', 'blocks', ['custom_name', 'project_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('proj_name_1', 'blocks', type_='unique')
    # ### end Alembic commands ###
