"""fix error with user_project model

Revision ID: fc68b7aa01e7
Revises: c42ec4771f1b
Create Date: 2024-11-07 13:48:14.925698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc68b7aa01e7'
down_revision: Union[str, None] = 'c42ec4771f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
