name: CI
on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22.20.0

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run linter
        working-directory: ./frontend
        run: npm run lint

  lint-core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'

      - name: Run flake8
        uses: py-actions/flake8@v2
        with:
          exclude: "core/alembic/versions/"
          path: "core"

  build:
    name: Build docker image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: frontend
          - context: core
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.context }}
          tags: |
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
      
      - name: Define build args
        id: define_build_args
        run: |
          if [ "${{ matrix.context }}" == "frontend" ]; then
            echo "BUILD_ARGS=NEXT_PUBLIC_API_URL=${{ secrets.BUILD_API_URL }}" >> $GITHUB_ENV
          else
            echo "BUILD_ARGS=" >> $GITHUB_ENV
          fi

      - name: Build and push docker images
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: ${{ env.BUILD_ARGS }}
